### ISSUE TITLE
Mod not working with 1060 server version.

### ISSUE THREAD

**Issue by AlexanderCurl** [leiizko/cod4_new_experience#1]
Hi!

First of all, keep up the good job, nice work, however this modification doesn't work with the 1060 release.
I don't want to update my servers, because the b3 won't work with them, so can you make it works with 1060 release please?

**Comment by leiizko** [comment]
Hello,

Sadly that release is too old and it does not include functions this modification relies on. However you can update your server and make your b3 work with it. I've made a quick tutorial on how to make it work with latest CoD4X version, you can find it [here](https://cod4x.me/forum/thread-1061.html).

**Comment by AlexanderCurl** [comment]
Awesome, thanks!
