### ISSUE TITLE
menu (esc) not usable during killcam

### ISSUE THREAD

**Issue by D4edalus** [leiizko/cod4_new_experience#11]

**Comment by leiizko** [comment]
Which menu? Right now "class" menu should be available so you can change loadout during it. The custom killcam requires me to disable menu rendering so default killcam style won't show.

Sadly right now it is limited to it but I am looking for a better solution, ideally some way to trick the client that killcam isn't playing while it is. Maybe in the future if something I can use gets implemented into 1.8. (ESC key detection, menu manipulation? Hint hint;) )

**Comment by D4edalus** [comment]
sorry for the way too short description. what i ment is that i can open the menu on esc, but i can't press any of the buttons there while the killcam is on. in my case i got killed and was about to ragequit the server - didn't work as i wasn't able to click the 'quit' button xD. 

I didn't check if that problem is special to your killcam, or is present in general. disabling menu rendering might explain it, how are you doing that?

**Comment by leiizko** [comment]
It looks like pressing the "leave game" button will open another menu which doesn't get shown during killcam.

On the start of the killcam I set client dvar "ui_ShowMenuOnly" to "class", and on the end resetting it. Meanwhile menu script listens for any menu response and if it happens during killcam it resets the dvar, however only chose a class and change team buttons actually produce menu response.

It is far from perfect but it is the only way I know of so far that will prevent stock killcam from showing.
