### ISSUE TITLE
fov,cmd,fps commands make work with b3

### ISSUE THREAD

**Issue by AlexanderCurl** [leiizko/cod4_new_experience#12]
Hi!

Can you explain how can I make this commands works with b3 please? I have everything installed, but no idea how can I add these commands to work.

**Comment by leiizko** [comment]
You need a customcommand B3 plugin first, then add in its config:
`fps = cmd fps:<PLAYER:PID>`
`fov = cmd fov:<PLAYER:PID>`
`promod = cmd promod:<PLAYER:PID>`

**Comment by AlexanderCurl** [comment]
you are the man, I suggest add these details in the readme as well! Thanks.

**Comment by sajjadssss** [comment]
How to add fov command and fps to b3
