### ISSUE TITLE
Add more gametypes to the mod

### ISSUE THREAD

**Issue by AlexanderCurl** [leiizko/cod4_new_experience#13]
I suggest to add more gametypes, for example, sd, sab, what else is officially supported by the game.

**Comment by leiizko** [comment]
It is possible I will unlock all gametypes in next update if they still work properly. Before it was pointless as one AGM could kill an entire team in SnD but now you can disable that so I guess it should become supported.

It will however take a while as next update will be a large one.

**Comment by leiizko** [comment]
Added in latest update. Unsure how some of the gamemodes will perform so beware.
