### ISSUE TITLE
Mapvote

### ISSUE THREAD

**Issue by Trawis** [leiizko/cod4_new_experience#14]
Why when I add my own (health) bar, mapvote huds become dark and you can't read anything?

P.S. Can you add gametype next to map name so players can vote for different gametypes?

**Comment by leiizko** [comment]
Just remove the bar on game end, it might have higher priority than mapvote hud, thus making it all messed up.

Once (if) I add other gametype support I might add a quick gametype vote after the map has been voted.

**Comment by leiizko** [comment]
gametype vote has been added in dev branch. It will be merged into main soon.
