### ISSUE TITLE
Spawn Protection Suggestion

### ISSUE THREAD

**Issue by Kingwolf123** [leiizko/cod4_new_experience#16]
I was testing the scripts. Whenever a player moves or fires while the spawn protection is on, the timer discontinues.
I am no expert on this, but logically we want spawn protection so that players who are camping specifically to kill newly spawned players cannot do so. So if this newly spawned player has found the camper's location, then he would want to kill him so, but as he moves or fires his spawn protection is disabled, so he may die again.
Do comment your views as well.

**Comment by Trawis** [comment]
That's how spawn protection works, why would you have protection and then shoot to other players? This is just so you can't be killed on spawn and so you can't shoot right after spawn.
Personally I like this, maybe just don't hide weapons because when I start to move it takes some time to switch to my weapon and then I'm killed.

**Comment by Kingwolf123** [comment]
That is a good explanation.
It would not really make a difference if weapons are hidden or not game wise. However, it does feel a little off waiting for the weapon switch before attacking, but that could be just me.

**Comment by leiizko** [comment]
Trawis already made a good explanation why it is how it is.

About the wait time, not disabling weapons can get really abusive as you are both invisible and invulnerable during spawn protection so if a player manages to pull a good rush into enemy team he will just get absolutely destroyed by spawning players. It gives an attacking player a chance to (barely) react.

Also if you want to shoot in first second of spawn protection it will start shooting with minimal (you can barely notice it) delay. Doing a fast weapon switch, which everyone does these days, will also cut this delay almost down to nothing.

**Comment by Kingwolf123** [comment]
Good Points made by everyone.
