### ISSUE TITLE
Grenade gravity

### ISSUE THREAD

**Issue by Koajakins** [leiizko/cod4_new_experience#18]
I dont know whether it is a bug or not, but me and Hagz realised that the grenades using this script when thrown generally explode before they hit the ground, seems to have an effect on the gravity (maybe effected by the increased movement speed and jump I dont know) 

If it is intended then you can close this of course, but as a suggestion if its a bug, maybe creating a CVAR will help users decide whether they want to set it or not. 

Many thanks

**Comment by Kingwolf123** [comment]
Yeah the jump duration is a bit higher in this, could be that gravity is set a little lower and hence nades explode in air.

**Comment by Koajakins** [comment]
Possibility that Leiizko set the gravity overall and didnt consider nades coming into play with that. Guess will wait and see if its intended or not.

**Comment by leiizko** [comment]
The gravity is a bit lower when fast paced mode is enabled, however gravity should have no impact on other entities but players themselves. 

Also in fast paced mode the overall speed is increased so nades get thrown farther. Maybe that's what is causing the behaviour you experienced?

In any case if you set dvar "fast_paced" to 0 it will be like in stock gameplay.

**Comment by Koajakins** [comment]
I will put it down to fast_paced being set to 1. 
Thanks Leiizko
