### ISSUE TITLE
Change default filmtweaks settings

### ISSUE THREAD

**Issue by AlexanderCurl** [leiizko/cod4_new_experience#2]
Hi!

I've installed your mod the new stable cod4x18 release, works fine, but I can't integrate with my filmtweaks settings.
I already checked all the scripts, but without luck..
Can you help?
Regards.

**Comment by leiizko** [comment]
Well this one is a bit anoying to change at the moment but filmtweaks are currently at:
[player.gsx](https://github.com/leiizko/cod4_new_experience/blob/master/code/player.gsx#L172-L179),
[scriptcommands.gsx](https://github.com/leiizko/cod4_new_experience/blob/master/code/scriptcommands.gsx#L100-L107),
[spectating.gsx](https://github.com/leiizko/cod4_new_experience/blob/master/code/spectating.gsx#L103-L110),
[rcon_commands.gsx](https://github.com/leiizko/cod4_new_experience/blob/master/code/rcon_commands.gsx#L96-L103),
[common.gsx](https://github.com/leiizko/cod4_new_experience/blob/master/code/common.gsx#L74-L81)

reminder for me: centralise the vision settings

**Comment by AlexanderCurl** [comment]
Yeah I found these settings, but every time I changed, nothing happened after SetNakedVision.

**Comment by leiizko** [comment]
oh wait, are you talking about filmtweaks you get by invoking "promod" command or are you trying to implement your own, that would be active all the time? 

If you want the latter, change all settings I linked you in previous post, disable the ability to use promod and fps command ( cmd_fps 0, cmd_promod 0 ) and finally hardcode it to stay on [here](https://github.com/leiizko/cod4_new_experience/blob/master/code/player.gsx#L73-L78). Just change promodTweaks to 1 and fullbright to 0

**Comment by AlexanderCurl** [comment]
No, I'm talking about definitive filmtweak change, so without invoking commands. I've written a filmtweaks.gsx and included to the globallogic.gsx after OnPlayerConnect callback when player has been connected the filmtweak settings applies.
I want to add this, but it's really tricky.

**Comment by leiizko** [comment]
Well if you already have a script written you could just thread it on spawn. You can do that in [player onSpawn function](https://github.com/leiizko/cod4_new_experience/blob/master/code/player.gsx#L7)

However you would still want to disable promod script command (set cmd_promod 0) and hardcore it to be always off by changing the variable to 0 [here](https://github.com/leiizko/cod4_new_experience/blob/master/code/player.gsx#L77)

Also you should replace [this](https://github.com/leiizko/cod4_new_experience/blob/master/code/common.gsx#L73-L84) code with a thread to your script. This should be the easiest way to achieve what you want
