### ISSUE TITLE
Cg_Reliable Commands Cycled Out on Player Joining

### ISSUE THREAD

**Issue by Kingwolf123** [leiizko/cod4_new_experience#21]
Hello,
Some Players when connecting get shown the following message Cg_Reliable Commands Cycled Out when the map is loaded. ( Dont Remember the Exact Message).
I havent Looked at the Server Logs yet, as to what is the issue serverside.

Oh and when a player times out, the server sends a command over flow message and there is a hitch / Freeze in the server (Windows). Why would that be?

Regards,
Kingwolf

**Comment by leiizko** [comment]
Are you maybe using custom waypoints for ending/credits with the latest commit?

It is possible that the players that get disconnected for overflow are simply lagging as the mod is pretty light on client commands.

**Comment by Kingwolf123** [comment]
Yeah just modified the text for the opening and ending credits etc,but that should not essentially make any difference right? . Didn't add any code.
Overflow happens when a player is basically going to timeout, but instead he overflows.
And its kinda annoying only because the server freezes as the player disconnects.
I Have added 2 Client Cvars ,that could be the problem.

**Comment by Kingwolf123** [comment]
Looks like there are about 133 Cvars for each client, these were the ones shown in the log. when the overflow message was shown.
How much is the buffer size?
It looks like my advertisments also add a healthy 10 Cvars to the total Cvars enforced Client Side.

**Comment by leiizko** [comment]
The buffer size is 128. But that doesn't mean that the limit of dvars you can set is 128 but it is the limit of dvars being sent to the client.

So it looks like they lagged so hard the server couldnt sent the commands for quite some time.

This issue should be a bit less common in the next mod update, as quite a few stat calls will be trimmed when player filesystem support arrives.

**Comment by Kingwolf123** [comment]
Yes basically they are not connected to the serer and are shown as 999, as they have been disconnected from the server. 
So it means that my client dvar list exceeds the maximum capacity that is provided by cod4x. it is around 133-137. But how else to reduce them? I will start looking at each Client Dvar individually and see if something can be done about it.

Thanks.

**Comment by Kingwolf123** [comment]
The players disconnecting upon connecting seem to load the map slower. Is there some constantly updated Dvar which gets cycled out for such players who take longer to load the map.?
 I have also noticed that some of these players have high pings. Mabye the server could not send the dvars to the clients in time and hence the cycled out error.

**Comment by leiizko** [comment]
This issue should be a bit less frequent now, some may still experience it tho, there is no way of avoiding that.

That message just means that the player didn't install cod4x client patch.

**Comment by Kingwolf123** [comment]
Good Stuff mate.
Will report any issues in this update. 
Cheers.

**Comment by Kingwolf123** [comment]
The situation is better.
There is more chance of player disconnecting with this issue as the amount of players in the server increases.

**Comment by leiizko** [comment]
Makes sense as more players put more stress on the server. In any case this is as good as it's gonna get.
