### ISSUE TITLE
Sometimes Players are shown more money that they have

### ISSUE THREAD

**Issue by Kingwolf123** [leiizko/cod4_new_experience#22]
Hello

I have noticed often that the money shown to the player on screen increases automatically (without the players doing any kills) sometimes. The true value of the player's money remains the same.
So sometimes if a player has $10 , then it just starts to increase and the player is shown something like $210 Dollars etc ( Increase is incremental and not sudden)
The True Money Value of the player remains the same. So if the player has $10 and he is shown $210 and he attempts to buy a UAV, He will be shown the missing Money message, which would be $10 if the hud is priced at $20.

Kindly look into the issue.

**Comment by leiizko** [comment]
Just a quick note: Players get money for "UAV assist" now, meaning if they called in an UAV recon, they will get +1$ for every kill his teammates do while UAV is online.
