### ISSUE TITLE
True Skill Questions

### ISSUE THREAD

**Issue by Kingwolf123** [leiizko/cod4_new_experience#24]
Hello,
Is the Cod4x True Skill Plugin a script or a seperate C Plugin for Cod4X?

**Comment by leiizko** [comment]
It is a still unfinished C++ plugin for CoD4X.

**Comment by Kingwolf123** [comment]
Oh because if i use invoke the skill command, i get a 0 value for the true skillpoints.

**Comment by leiizko** [comment]
Well once it will be fully implemented, the skill will be 0 the first game you play. After that it will slowly converge on players real skill.
Note that huge TDM servers won't really benefit from it (the pool of games needed to get the reliable is insane), meanwhile the FFA servers will quickly achieve this (as low as 3 games).

It is a system that could be used if a competitive mod gets added to CoD4X (or for any ~5v5 promod server for that matter) and it will be implemented here as a kind of tech demo.

**Comment by Kingwolf123** [comment]
For Promod as well?
Very Interesting and good work.
This would be the benchmark for competitive promod players if  even a part of the vision is realized and implemented.

**Comment by leiizko** [comment]
The plugin will be usable with any mod, competitive ones make the most sense.

To have a benchmark there would have to be a dedicated database for the ranks which I don't really see happening. Maybe if competitive mode makes its way into the CoD4X.

We shall see what the future holds.
