### ISSUE TITLE
Script Runtime Errors

### ISSUE THREAD

**Issue by Kingwolf123** [leiizko/cod4_new_experience#25]
^1******* script runtime error *******
pair 'fullbright;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 139)
 array[ array.size ] = "fullbright;" + self.pers[ "fullbright" ];
                                     *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

^1******* script runtime error *******
pair 'fov;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 140)
 array[ array.size ] = "fov;" + self.pers[ "fov" ];
                              *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

^1******* script runtime error *******
pair 'promodTweaks;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 141)
 array[ array.size ] = "promodTweaks;" + self.pers[ "promodTweaks" ];
                                       *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

^1******* script runtime error *******
pair 'hardpointSType;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 142)
 array[ array.size ] = "hardpointSType;" + self.pers[ "hardpointSType" ];
                                         *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

^1******* script runtime error *******
pair 'killcamText;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 143)
 array[ array.size ] = "killcamText;" + self.pers[ "killcamText" ];
                                      *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

^1******* script runtime error *******
pair 'mu;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 144)
 array[ array.size ] = "mu;" + self.pers[ "mu" ];
                             *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

^1******* script runtime error *******
pair 'sigma;' and 'undefined' has unmatching types 'string' and 'undefined': (file 'code/player.gsx', line 145)
 array[ array.size ] = "sigma;" + self.pers[ "sigma" ];
                                *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4264)
   self thread code\player::FSSave();
               *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 49)
 [[level.callbackPlayerDisconnect]]();
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 46)
CodeCallback_PlayerDisconnect()
*
^1************************************

**Comment by Kingwolf123** [comment]
Kindly Check these.

**Comment by leiizko** [comment]
Try the latest commit please and let me know if it still happens.

**Comment by Kingwolf123** [comment]
Fixed.
