### ISSUE TITLE
Add admin

### ISSUE THREAD

**Issue by cyyborg** [leiizko/cod4_new_experience#26]
Hi, how do I add admin or grant permissions to the players?

**Comment by Kingwolf123** [comment]
There is some mention of a VIP system for New Experience, but i havent tested or used it yet.

**Comment by leiizko** [comment]
This isn't a NE thing but you can add it with rcon command "adminaddadmin <player> <power>", player must have steam running. If you need any more help refer to [CoD4x.me](cod4x.me)

VIP system isn't added yet and will most likely include only icon on scoreboard and special welcome.
