### ISSUE TITLE
SD each round killcam.

### ISSUE THREAD

**Issue by AlexanderCurl** [leiizko/cod4_new_experience#27]
Addition: add a killcam in every round, and a grace period before the round starts (5 secs).

**Comment by leiizko** [comment]
Killcam has been fixed and strat has been added. (set strat 1)
Note that spawn protection interferes with strat so be sure to disable it (not needed in SnD anyway)

Please report back if everything works as it should.

**Comment by AlexanderCurl** [comment]
Yes, it is working now as you expected.
