### ISSUE TITLE
Script error while specting.

### ISSUE THREAD

**Issue by TomiAlvesCardoso** [leiizko/cod4_new_experience#29]
---------------------------
when someone try to spect, does not crash the server until some days
---------------------------
^1******* script runtime error *******
cannot cast undefined to bool: (file 'scripts/spectating.gsx', line 50)
   else if( self.pers[ "spec_keys" ] )
                     *
^1started from:
(file 'scripts/spectating.gsx', line 83)
    wait 0.3;
    *
^1************************************

^1******* script runtime error *******
cannot cast undefined to bool: (file 'scripts/spectating.gsx', line 50)
   else if( self.pers[ "spec_keys" ] )
                     *
^1started from:
(file 'scripts/spectating.gsx', line 85)
    wait 0.3;
    *
^1************************************

^1******* script runtime error *******
cannot cast undefined to bool: (file 'scripts/spectating.gsx', line 50)
   else if( self.pers[ "spec_keys" ] )
                     *
^1started from:
(file 'scripts/spectating.gsx', line 85)
    wait 0.3;
    *
^1************************************

^1******* script runtime error *******
cannot cast undefined to bool: (file 'scripts/spectating.gsx', line 50)
   else if( self.pers[ "spec_keys" ] )
                     *
^1started from:
(file 'scripts/spectating.gsx', line 85)
    wait 0.3;
    *
^1************************************

^1******* script runtime error *******
cannot cast undefined to bool: (file 'scripts/spectating.gsx', line 50)
   else if( self.pers[ "spec_keys" ] )
                     *
^1started from:
(file 'scripts/spectating.gsx', line 85)
    wait 0.3;
    *
^1************************************
Say asu_nya: se va solito

^1******* script runtime error *******
cannot cast undefined to bool: (file 'scripts/spectating.gsx', line 50)
   else if( self.pers[ "spec_keys" ] )
                     *
^1started from:
(file 'scripts/spectating.gsx', line 85)
    wait 0.3;
    *
^1************************************

**Comment by leiizko** [comment]
self.pers[ "spec_keys" ] is not defined.

This however doesn't concern the NE mod and I don't provide support for implementing scripts into third party mods.

**Comment by TomiAlvesCardoso** [comment]
thanks, can you deleted this? since it was my error
