### ISSUE TITLE
Maprotate

### ISSUE THREAD

**Issue by SinnerX96** [leiizko/cod4_new_experience#3]
At the end of some maps, that ending part (showing kills,deaths,headshots) doesn't show up and map does not get rotated

**Comment by leiizko** [comment]
Any error log? Did you change something? It's impossible for this to happen without something going horribly wrong

**Comment by SinnerX96** [comment]
I did not changed anything,Does not always happen,like twice a day

**Comment by jebaczmajeva** [comment]
It happens to me too.

**Comment by leiizko** [comment]
Do you use killstreak or shop based hardpoints?

**Comment by jebaczmajeva** [comment]
Killstreak based. It went away after disabling final killcam. Again, temp fix. But I love your work <3
