### ISSUE TITLE
B3 custom cmds not working 

### ISSUE THREAD

**Issue by morlockonzark** [leiizko/cod4_new_experience#31]
even i enabled in config as you described .. i am not able to work some cmd for b3 like fov fps and some custom rounds like sniper knife jumpmode

**Comment by leiizko** [comment]
[#12](https://github.com/leiizko/cod4_new_experience/issues/12)
Also make sure "rcon_interface" is set to 1.

And there are no commands for custom rounds.

**Comment by morlockonzark** [comment]
i did but b3 not respond at all for !fps !fov  and !sniper !jumpmode !knife round not working .. without script those working fine with any mod or without mod

**Comment by leiizko** [comment]
Like I said before sniper.. etc commands do NOT exist in this mod.
If B3 doesn't respond, that's not a mod's issue, try your luck on B3 support forums. If you follow instructions on the issue above it will work.
