### ISSUE TITLE
Implement MySQL for playerstats

### ISSUE THREAD

**Issue by Kingwolf123** [leiizko/cod4_new_experience#35]
Cod4x has added the ability to interact to MySQL Databases ( upto 4 ) directly from .gsc scripts,
If the player stats are shifted to be stored in a MySQL, it would make them more manageable and flexible, not to mention efficient.

What do you think?

**Comment by leiizko** [comment]
Well using mysql database was my initial idea but eventually I decided against it as many people would have problems installing this mod.
Right now you just drop the scripts in and it works out of the box but mysql database requires an extra plugin (only available in source code) and actual database. Not many admins would be able to set it all up in my opinion.

Perhaps HTTP plugin will be an option in the future (unsure if works on windows as only linux version is available) as it would solve few problems with simpler installation.

**Comment by Kingwolf123** [comment]
Add Proper Instructions in the how to install ?
People who cant follow them and setup a simple database shouldn't be hosting servers anyways

**Comment by leiizko** [comment]
Decided I will add this once everything else is done.

**Comment by T-Maxxx** [comment]
https://github.com/callofduty4x/mysql/tree/master/bin

**Comment by leiizko** [comment]
Done
