### ISSUE TITLE
Killcam being black and white

### ISSUE THREAD

**Issue by jebaczmajeva** [leiizko/cod4_new_experience#4]
Sometimes, probably after user used predator

**Comment by jebaczmajeva** [comment]
And it is stuck the whole game for that player like that.

**Comment by leiizko** [comment]
It's a feature, killcam will use whatever vision the killer had at the moment of the kill however it should revert back to your specific vision after the killcam is over.
Do you maybe have some errors in your logs about this?

**Comment by jebaczmajeva** [comment]
No errors in log, but it does not revert. I fixed it by removing setdvars from common????, but that is just a workaround :/

So basically, someone uses a predator, killcam from that player stays "thermal" till the end of the game.

**Comment by leiizko** [comment]
Please try the latest version if it still happens.
