### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cyyborg** [leiizko/cod4_new_experience#40]
Error: 
******* script compile error *******
Error: bad token '#': (file 'maps/mp/gametypes/_globallogic.gsx', line 1174)
#if isSyscallDefined TS_Rate
*
************************************
----- Server Shutdown -----

With the reason: Server fatal crashed: script compile error
bad token '#'
#if isSyscallDefined TS_Rate
(see console for details)

**Comment by leiizko** [comment]
You're using too old version for the mod to run. Compile the latest code in cod4x masterbranch to run it.

**Comment by cyyborg** [comment]
-----------------------------
 CoD4X Auto Update
 Current version: 1.8
 Current subversion: 17.5
 Current build: 2055
-----------------------------

New subversion 17.5
Update not needed. All files are equal.

**Comment by leiizko** [comment]
Auto update has about 100 commits older version. Like I said compile masterbranch from github and it will work.

**Comment by cyyborg** [comment]
ok, Thank you
