### ISSUE TITLE
command ingame

### ISSUE THREAD

**Issue by cyyborg** [leiizko/cod4_new_experience#42]
Default : Command name, this is used to invoke the command ingame with $.
my question: It can be changed by the sign ! to invoke the commands?

**Comment by volkv** [comment]
@cyyborg 
`set g_disabledefcmdprefix 0`

**Comment by cyyborg** [comment]
Where do I put that command? in server.cfg or in config.cfg?

**Comment by leiizko** [comment]
Wherever, It's a CoD4X server dvar. However you will be unable to use B3 if you use this.

**Comment by cyyborg** [comment]
ok , thank you very much
