### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Gilly901** [leiizko/cod4_new_experience#46]
******* script runtime error *******
pair 'forfeit, win: ' and 'undefined' has unmatching types 'string' and 'undefined': (file 'maps/mp/gametypes/_globallogic.gsx', line 244)
  logString( "forfeit, win: " + winner + ", allies: " + game["teamScores"]["allies"] + ", opfor: " + game["teamScores"]["axis"] );
                              *
started from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 210)
 wait (10.0);
 *
************************************

**Comment by leiizko** [comment]
Not a NE bug, it is also non-critical and won't crash a server unless in developer mode.
