### ISSUE TITLE
ac130_40mm

### ISSUE THREAD

**Issue by cyyborg** [leiizko/cod4_new_experience#48]
the ac130 strip 40mm infinitely, can be limited as the 105mm to 4 or 6? wait to reload and shoot again

**Comment by leiizko** [comment]
Fire rate is taken from single player. Fell free to change it to your liking for your server - [ac130@L354](https://github.com/leiizko/cod4_new_experience/blob/master/code/ac130.gsx#L354)

**Comment by cyyborg** [comment]
I do not really know how to change, could you say? and thank you very much your mod is very good the best that I have found

**Comment by leiizko** [comment]
Change the number 600 to whatever you want. 1000 means 1 second, so to have it shoot every 4 seconds change it to 4000.

**Comment by cyyborg** [comment]
Ok, thanks
