### ISSUE TITLE
error - breaks the server a few seconds

### ISSUE THREAD

**Issue by cyyborg** [leiizko/cod4_new_experience#50]
Client: 2 lost reliable commands
===== pending server commands =====
cmd    36: 23756500: d 748 
cmd    37: 23756500: d 750 
cmd    39: 23756650: d 744 
cmd    40: 23757800: d 744 
cmd    41: 23757800: d 754 
cmd    42: 23757800: d 748 
cmd    43: 23757800: d 750 
cmd    44: 23757800: d 753 
cmd    45: 23758300: d 754 
cmd    46: 23758650: d 744 
cmd    47: 23758950: d 748 
cmd    48: 23759050: d 1411
cmd    49: 23759750: d 755 
cmd    50: 23760000: d 748 
cmd    51: 23760000: d 750 
cmd    52: 23760000: d 753 
cmd    53: 23760000: d 754 
cmd    54: 23762050: d 748
cmd    55: 23762300: d 746 
cmd    56: 23763050: d 748 
cmd    57: 23763050: d 750 
cmd    58: 23763050: d 753 
cmd    59: 23764100: d 748 
cmd    60: 23764100: d 750 
cmd    61: 23764100: d 753 
cmd    62: 23764100: d 754 
cmd    63: 23764700: d 754 
cmd    64: 23764750: d 748 
cmd    65: 23764750: d 750 
cmd    66: 23764750: d 753 
cmd    67: 23766350: d 746 
cmd    68: 23767100: d 748 
cmd    69: 23767100: d 750 
cmd    70: 23767100: d 753 
cmd    71: 23767900: d 754 
cmd    72: 23767900: d 755 
cmd    73: 23767950: d 756 
^5Hitch warning: 764 msec frame time
Player Mrerni6^7, 2 dropped: EXE_SERVERCOMMANDOVERFLOW

**Comment by leiizko** [comment]
Can't do anything about it, it's more of a server issue. This mostly happens when there are heavy laggers present so maybe try limiting max ping.
