### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by nimataeb** [leiizko/cod4_new_experience#51]
dude ur script is great but i got this problem, im new to cod4 server hosting so forgive me if i sound like an idiot, i did everything u said and it gives me this: 
******* script compile error *******
Error: bad token '#': (file 'maps/mp/gametypes/_globallogic.gsx', line 1174)
#if isSyscallDefined TS_Rate
*
************************************
when i deleted that part, it gave me the same error with a line about mysql.

**Comment by leiizko** [comment]
[FAQ (second point)](https://cod4x.me/index.php?/forums/topic/2298-faq-read-before-posting/)
