### ISSUE TITLE
Killcam causes server hangs?

### ISSUE THREAD

**Issue by Xiggyy** [leiizko/cod4_new_experience#52]
Hey,

We had this issue when we were on the old build of COD4x but have since upgraded to the latest stable version [17.7] and still have the issue. Again with us, we're just looking for a bit of guidance. The issue isn't constant and I can't replicate it. It just happens randomly but the only denomination is to do with endgame kill cam. 

Here's the error that times out after a while and changes map -

** script runtime error **

undefined is not an array, string, or vector: (file 'code/spectating.gsx', line 132)

if( !isDefined( ent.pers[ "promodTweaks" ] ) )

called from:

(file 'code/spectating.gsx', line 41)

self thread visionSettingsForEnt( entity );

started from: (file 'code/spectating.gsx', line 25)

Any assistance would be fab and anything we can do to assist we'll do too!

Thanks.

**Comment by leiizko** [comment]
Try running the latest version of NE mod to see if it makes a difference.

**Comment by Xiggyy** [comment]
Much appreciated for that! We've installed it and will update you in a couple of days. 

Thanks!

**Comment by Xiggyy** [comment]
Seems like the server is stable. Thanks for that!
