### ISSUE TITLE
Server does not recognise the side script

### ISSUE THREAD

**Issue by TRAGEDYSA** [leiizko/cod4_new_experience#55]
I did just as u had instructed in the read me file.
Copied and pasted the code and maps files in server main_shared file.
Can u please help me as I am unable to play one of the best side scripts ever made.😢😢😢

**Comment by TRAGEDYSA** [comment]
Can u pls make a tutorial or explain it to me in person...

**Comment by leiizko** [comment]
A CoD4X server binary is required to run this scripts. You can get it on cod4x.me
