### ISSUE TITLE
custom maps

### ISSUE THREAD

**Issue by obteo** [leiizko/cod4_new_experience#56]
Hi leiizko, is it possible to run custom maps with the new experience?

thank you.

**Comment by leiizko** [comment]
A mod is required to run custom maps. You can keep scripts in main_shared and run a "fake" mod (empty folder). This way server will run a mod that makes no changes while scripts will still work.

**Comment by TRAGEDYSA** [comment]
Can we add custom modes sound files and weapon files to the main
shared folder?
