### ISSUE TITLE
Script runtime error

### ISSUE THREAD

**Issue by twitchq** [leiizko/cod4_new_experience#57]
Hi, I have quite a few errors:
`^1******* script runtime error *******
undefined is not an entity: (file 'code/hardpoints.gsx', line 97)
 self.StatusHud_Deaths Destroy();
      *
^1called from:
(file 'code/events.gsx', line 69)
  self thread [[level.events[ "PlayerKilled" ][ i ]]]( eInflictor, attacker, iDamage, sMeansOfDeath, sWeapon, vDir, sHitLoc, psOffsetTime, deathAnimDuration );
                                              *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 5203)
 self thread code\events::onPlayerKilled(eInflictor, attacker, iDamage, sMeansOfDeath, sWeapon, vDir, sHitLoc, psOffsetTime, deathAnimDuration);
             *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 70)
 [[level.callbackPlayerKilled]](eInflictor, eAttacker, iDamage, sMeansOfDeath, sWeapon, vDir, sHitLoc, timeOffset, deathAnimDuration);
         *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 67)
CodeCallback_PlayerKilled(eInflictor, eAttacker, iDamage, sMeansOfDeath, sWeapon, vDir, sHitLoc, timeOffset, deathAnimDuration)
*
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4811)
 self finishPlayerDamage( eInflictor, eAttacker, iDamage, iDFlags, sMeansOfDeath, sWeapon, vPoint, vDir, sHitLoc, psOffsetTime );
      *
^1called from:
(file 'maps/mp/gametypes/_globallogic.gsx', line 4740)
   self finishPlayerDamageWrapper(eInflictor, eAttacker, iDamage, iDFlags, sMeansOfDeath, sWeapon, vPoint, vDir, sHitLoc, psOffsetTime);
        *
^1called from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 60)
 [[level.callbackPlayerDamage]](eInflictor, eAttacker, iDamage, iDFlags, sMeansOfDeath, sWeapon, vPoint, vDir, sHitLoc, timeOffset);
         *
^1started from:
(file 'maps/mp/gametypes/_callbacksetup.gsx', line 57)
CodeCallback_PlayerDamage(eInflictor, eAttacker, iDamage, iDFlags, sMeansOfDeath, sWeapon, vPoint, vDir, sHitLoc, timeOffset)
*
^1************************************
Say ExMachina: ^^`

Is there any solution to this problem?

**Comment by leiizko** [comment]
This is not a part of original code. I cannot offer support for customized versions of this mod.
