### ISSUE TITLE
Cannot run cmd commands using rcon

### ISSUE THREAD

**Issue by waseem-h** [leiizko/cod4_new_experience#58]
Hi, I get the following error when running any commands like /rcon stats, /rcon shop etc. It looks like it can't find `self` or the player when calling these commands? Is there something I am doing wrong? 
![Call of Duty 4  Modern Warfare Screenshot 2020 04 22 - 14 15 20 31](https://user-images.githubusercontent.com/34707418/79980716-d49fce80-84a3-11ea-9a50-298bc7bef0ef.png)

I want to see my own stats using the rcon command on my client only. Shouldn't /rcon stats:<my-id> work out of the box?

**Comment by leiizko** [comment]
You are using it wrong. These commands are not invoked via rcon. Proper use is to type in chat (or console for that matter) $ followed by command name, example: $stats

Rcon interface is there only for use with management tools like BigBrotherBot. How to use it is described at the end of readme.
