### ISSUE TITLE
how can i enable all weaons and classes for all users?

### ISSUE THREAD

**Issue by gihanrangana** [leiizko/cod4_new_experience#60]
i have setup the server with this.but users have to promote there skills with playing the server.i have level 55 profile but when i logged in to server i have to go with level 1.how can i fix this?

**Comment by leiizko** [comment]
As this is ran as server side mod it will have no effect on your rank. You either have rank 55 in a separate mod or your profile is broken.

If you are by any chance running 2.x version - that is more of a tech demo and not really meant to be run on public server.
