### ISSUE TITLE
about mysql plugin

### ISSUE THREAD

**Issue by gihanrangana** [leiizko/cod4_new_experience#61]
i can't use mysql plugin its getting this error 
`Error: This plugin might not be compatible with this server version! Requested plugin handler version: 3.100, server's plugin handler version: 4.0. Unloading the plugin...`

**Comment by leiizko** [comment]
Maintainers of mysql plugin did not update it to work with new arch version of the server. Unless someone bothers to make it compatible it will stay broken indefinetly.
