### ISSUE TITLE
[Question] Set kill XP addition/stack timer (+100,+200 etc.) to default

### ISSUE THREAD

**Issue by tangowango** [leiizko/cod4_new_experience#62]
Hello.
First of all, thanks for the amazing mod. I'd like to set the time required to make the kill XP stack/add to the default value. It seems to be increased in CoD4 New Experience. I know that the XP modifier count (+10, +100, +1000) can be changed with  xp_multi "x" or "registerScoreInfo" in _rank.gsc, but couldn't find anything regarding the required time in-between kills.  I know it's a trivial thing, but I reckon quite a few people care about it. Thanks in advance.

**Comment by leiizko** [comment]
This is actually unchanged. However if you would like to reduce it, you can do it [here](https://github.com/leiizko/cod4_new_experience/blob/master/maps/mp/gametypes/_rank.gsx#L1008-L1014)
