### ISSUE TITLE
Modular feature

### ISSUE THREAD

**Issue by syaifulnizamyahya** [leiizko/cod4_new_experience#63]
This mod provide lots of useful 'Quality of Life' features. Is it possible to separate the QOL features from additional gameplay changes?

QOL features
1. XP multiplier mode
2. Fast paced mode
3. FOV settings
Thanks.

**Comment by leiizko** [comment]
You can disable almost everything with cvars in config file. Only thing that can't really be removed is the killcam look. 

Otherwise i have no plans for any other changes to the base mod.
