### ISSUE TITLE
Menu does not shows after joining spectator

### ISSUE THREAD

**Issue by SinnerX96** [leiizko/cod4_new_experience#8]

**Comment by leiizko** [comment]
Which menu? Under what circumstances? I'm unable to reproduce this issue.

**Comment by SinnerX96** [comment]
only sometimes happen when I switch spec and after a while I wanted to join a team but when I press Esc the menu did not showed

**Comment by leiizko** [comment]
Did you switch to spec during killcam?

**Comment by SinnerX96** [comment]
sorry I really don't remember that :(

**Comment by SinnerX96** [comment]
Okay this is the bug despite all mentioned above.
I was playing and got killed,during the killcam I switched to spec and then I typed /disconnect 
after that game quits and comes to the game's main menu,but menu's tabs are not showing only a blackscreen which only shows cod4x version bottom of the screen

**Comment by leiizko** [comment]
For future reference, if you disconnect during the killcam the menus will be gone, sadly there is no way to prevent this without giving up the custom killcam alltogether. 
However there was a bug that would make menus dissapear if you went to spectator after being killed atleast once. It should not happen again.

So if you want to disconnect, just wait or skip( if possible ) the killcam and then do it. You could also quit the whole game (/quit) and the issue won't happen.

**Comment by SinnerX96** [comment]
Disabling the menu during the killcam would be better I guess
