### ISSUE TITLE
weapon shop buttons

### ISSUE THREAD

**Issue by D4edalus** [leiizko/cod4_new_experience#9]
maybe using moveforward/backward buttons would be more intuitive to use than the melee button. 

https://github.com/callofduty4x/CoD4x_Server/blob/5222e3e8746348ada01ed0fc84545c61a5b41121/src/scr_vm_main.c#L559-L574

**Comment by leiizko** [comment]
I have thought of it and I will probably let it be dvar controlled (or even player controlled).

Both methods have ups and downs, currently you can move around while selecting but you can pick dropped weapons which is annoying and also knifing all over the place..

With move buttons I would have to set the player's speed to 0 (if I disable controls, you wouldn't be able to close the shop without buying something) and that may feel really clunky.

It comes down to personal taste I guess.

**Comment by D4edalus** [comment]
yeah i wasnt sure either. but while playing, especially at the beginning, i found it a hassle to each time search for the buttons. also if players changed melee and use to different keys they might not be next to eachother, but that's virtually always the case for moveforward/backward.
but yeah, its both far from perfect :D
